import { Cliente, OrdemServico } from '@/types';

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: 'cli-001',
    nome: 'Carlos Eduardo Silva',
    telefone: '(11) 98765-4321',
    cpf: '123.456.789-00',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'cli-002',
    nome: 'Mariana Santos',
    telefone: '(11) 99887-6655',
    cpf: '234.567.890-11',
    created_at: '2026-08-05T14:30:00Z',
  },
  {
    id: 'cli-003',
    nome: 'Roberto Almeida',
    telefone: '(11) 97123-8899',
    cpf: '345.678.901-22',
    created_at: '2026-08-08T09:15:00Z',
  },
  {
    id: 'cli-004',
    nome: 'Fernanda Lima',
    telefone: '(11) 98111-2233',
    cpf: '456.789.012-33',
    created_at: '2026-08-12T16:00:00Z',
  },
  {
    id: 'cli-005',
    nome: 'Lucas Oliveira',
    telefone: '(11) 99444-5566',
    cpf: '567.890.123-44',
    created_at: '2026-08-15T11:20:00Z',
  },
];

export const MOCK_ORDENS_SERVICO: OrdemServico[] = [
  {
    id: 'os-1001',
    numero_os: 1001,
    cliente_id: 'cli-001',
    cliente: MOCK_CLIENTES[0],
    tipo_dispositivo: 'iPhone',
    modelo: 'iPhone 14 Pro Max',
    cor: 'Roxo-profundo',
    imei_ou_serial: '358912345678901',
    senha_aparelho: '123456',
    buscar_iphone_desativado: true,
    defeito_reclamado: 'Vidro traseiro quebrado e câmera principal não foca após queda.',
    laudo_tecnico: 'Necessária substituição da tampa traseira a laser e módulo da câmera principal original.',
    checklist_entrada: {
      face_id: 'ok',
      true_tone: 'ok',
      cameras: 'defeito',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'ok',
      detalhes_esteticos: 'Trincados intensos na tampa traseira, arranhão leve na lateral inferior.',
      fotos_urls: [
        'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&auto=format&fit=crop&q=60',
      ],
    },
    status: 'em_manutencao',
    tipo_cobertura: 'Particular',
    localizacao_atual: 'bancada_local',
    data_entrada: '2026-08-17T09:00:00Z',
    previsao_entrega: '2026-08-20T17:00:00Z',
    valor_servico: 250.0,
    valor_pecas: 680.0,
    valor_desconto: 30.0,
    valor_total: 900.0,
    forma_pagamento: 'Pix',
    garantia_dias: 90,
    pecas: [
      {
        id: 'peca-1',
        os_id: 'os-1001',
        descricao: 'Módulo Câmera Traseira iPhone 14 Pro Max',
        tipo_qualidade: 'Original',
        custo: 350.0,
        preco_venda: 500.0,
        quantidade: 1,
      },
      {
        id: 'peca-2',
        os_id: 'os-1001',
        descricao: 'Tampa Traseira Roxo Profundo',
        tipo_qualidade: 'Primeira Linha',
        custo: 70.0,
        preco_venda: 180.0,
        quantidade: 1,
      },
    ],
    created_at: '2026-08-17T09:00:00Z',
  },
  {
    id: 'os-1002',
    numero_os: 1002,
    cliente_id: 'cli-002',
    cliente: MOCK_CLIENTES[1],
    tipo_dispositivo: 'iPhone',
    modelo: 'iPhone 15 Pro',
    cor: 'Titânio Natural',
    imei_ou_serial: '351234987654321',
    senha_aparelho: 'Desenho L',
    buscar_iphone_desativado: true,
    defeito_reclamado: 'Placa-mãe não liga e aquecimento excessivo ao tentar carregar.',
    laudo_tecnico: 'Curto-circuito na linha principal de alimentação vcc_main. Aparelho enviado para laboratório especialista em reparo avançado de placa em São Paulo.',
    checklist_entrada: {
      face_id: 'nao_se_aplica',
      true_tone: 'ok',
      cameras: 'ok',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'defeito',
      detalhes_esteticos: 'Aparelho em excelente estado sem marcas estéticas.',
      fotos_urls: [],
    },
    status: 'em_manutencao',
    tipo_cobertura: 'Particular',
    localizacao_atual: 'laboratorio_sp',
    detalhes_terceirizado: {
      parceiro_sp: 'Lab Micro-Solda SP Tech',
      rastreio_envio: 'SEDEX-SP991823',
      rastreio_retorno: 'SEDEX-SP994400',
      data_envio_sp: '2026-08-10',
      previsao_retorno_sp: '2026-08-16', // VENCIDO! (data atual é 2026-08-19) -> Dispara alerta visual!
      custo_laboratorio: 450.0,
      observacoes: 'Aguardando substituição do CI de carga Hydra.',
    },
    data_entrada: '2026-08-09T14:00:00Z',
    previsao_entrega: '2026-08-17T18:00:00Z',
    valor_servico: 350.0,
    valor_pecas: 450.0,
    valor_desconto: 0.0,
    valor_total: 800.0,
    forma_pagamento: 'Cartão de Crédito 3x',
    garantia_dias: 90,
    pecas: [
      {
        id: 'peca-3',
        os_id: 'os-1002',
        descricao: 'Serviço de Reballing e Troca de PMIC/Hydra SP',
        tipo_qualidade: 'Original',
        custo: 300.0,
        preco_venda: 450.0,
        quantidade: 1,
      },
    ],
    created_at: '2026-08-09T14:00:00Z',
  },
  {
    id: 'os-1003',
    numero_os: 1003,
    cliente_id: 'cli-003',
    cliente: MOCK_CLIENTES[2],
    tipo_dispositivo: 'iPad',
    modelo: 'iPad Air 5ª Geração',
    cor: 'Cinza Espacial',
    imei_ou_serial: 'DMPX9823KL12',
    senha_aparelho: '0000',
    buscar_iphone_desativado: false,
    defeito_reclamado: 'Retorno de Garantia da Loja: Touch screen apresentando toques fantasmas no canto esquerdo.',
    laudo_tecnico: 'Garantia coberta pela Fitch Tecnologia. Substituição da tela sem custo para o cliente.',
    checklist_entrada: {
      face_id: 'nao_se_aplica',
      true_tone: 'ok',
      cameras: 'ok',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'ok',
      detalhes_esteticos: 'Película levemente riscada.',
      fotos_urls: [],
    },
    status: 'aguardando_peca',
    tipo_cobertura: 'Garantia da Loja',
    localizacao_atual: 'bancada_local',
    data_entrada: '2026-08-18T10:30:00Z',
    previsao_entrega: '2026-08-21T12:00:00Z',
    valor_servico: 0.0,
    valor_pecas: 0.0,
    valor_desconto: 0.0,
    valor_total: 0.0,
    forma_pagamento: 'Garantia Interna',
    garantia_dias: 90,
    pecas: [
      {
        id: 'peca-4',
        os_id: 'os-1003',
        descricao: 'Tela Completa iPad Air 5 (Custo de Garantia)',
        tipo_qualidade: 'Original',
        custo: 380.0,
        preco_venda: 0.0,
        quantidade: 1,
      },
    ],
    created_at: '2026-08-18T10:30:00Z',
  },
  {
    id: 'os-1004',
    numero_os: 1004,
    cliente_id: 'cli-004',
    cliente: MOCK_CLIENTES[3],
    tipo_dispositivo: 'Apple Watch',
    modelo: 'Apple Watch Series 8 45mm',
    cor: 'Estelar',
    imei_ou_serial: 'FH2L9012MM33',
    senha_aparelho: '7788',
    buscar_iphone_desativado: false,
    defeito_reclamado: 'Troca de bateria (saúde 74%) e vedação d\'água.',
    laudo_tecnico: 'Bateria substituída com sucesso por peça original Apple. Vedação e teste de pressão OK.',
    checklist_entrada: {
      face_id: 'nao_se_aplica',
      true_tone: 'ok',
      cameras: 'nao_se_aplica',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'ok',
      detalhes_esteticos: 'Pulseira com marcas normais de uso.',
      fotos_urls: [],
    },
    checklist_saida: {
      face_id: 'nao_se_aplica',
      true_tone: 'ok',
      cameras: 'nao_se_aplica',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'ok',
      touch_display: 'ok',
      observacoes_saida: 'Testado 100%. Bateria 100% de saúde.',
      ok_tecnico: true,
      data_verificacao: '2026-08-19T11:00:00Z',
    },
    status: 'pronto_para_retirada',
    tipo_cobertura: 'Particular',
    localizacao_atual: 'loja_pronto',
    data_entrada: '2026-08-16T15:00:00Z',
    previsao_entrega: '2026-08-19T17:00:00Z',
    valor_servico: 150.0,
    valor_pecas: 220.0,
    valor_desconto: 20.0,
    valor_total: 350.0,
    forma_pagamento: 'Pix',
    garantia_dias: 90,
    pecas: [
      {
        id: 'peca-5',
        os_id: 'os-1004',
        descricao: 'Bateria Apple Watch S8 45mm Original',
        tipo_qualidade: 'Original',
        custo: 110.0,
        preco_venda: 220.0,
        quantidade: 1,
      },
    ],
    created_at: '2026-08-16T15:00:00Z',
  },
  {
    id: 'os-1005',
    numero_os: 1005,
    cliente_id: 'cli-005',
    cliente: MOCK_CLIENTES[4],
    tipo_dispositivo: 'Android',
    modelo: 'Samsung Galaxy S24 Ultra',
    cor: 'Titânio Violeta',
    imei_ou_serial: '357788990011223',
    senha_aparelho: '9900',
    buscar_iphone_desativado: false,
    defeito_reclamado: 'Display trincado sem imagem. Vidro e touch comprometidos.',
    laudo_tecnico: 'Instalação de Display OLED com Aro Original Samsung.',
    checklist_entrada: {
      face_id: 'nao_se_aplica',
      true_tone: 'nao_se_aplica',
      cameras: 'ok',
      microfones: 'ok',
      alto_falante: 'ok',
      carregamento: 'ok',
      detalhes_esteticos: 'Trincado acentuado na parte superior frontal.',
      fotos_urls: [],
    },
    status: 'orcamento_gerado',
    tipo_cobertura: 'Particular',
    localizacao_atual: 'bancada_local',
    data_entrada: '2026-08-19T08:30:00Z',
    previsao_entrega: '2026-08-20T18:00:00Z',
    valor_servico: 200.0,
    valor_pecas: 1100.0,
    valor_desconto: 50.0,
    valor_total: 1250.0,
    forma_pagamento: 'A definir',
    garantia_dias: 90,
    pecas: [
      {
        id: 'peca-6',
        os_id: 'os-1005',
        descricao: 'Tela OLED com Aro S24 Ultra',
        tipo_qualidade: 'OLED',
        custo: 750.0,
        preco_venda: 1100.0,
        quantidade: 1,
      },
    ],
    created_at: '2026-08-19T08:30:00Z',
  },
];
